"""Update company table

Revision ID: 4a9b257b7545
Revises: 6dedb0a8fc0b
Create Date: 2025-05-23 12:59:01.155543

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a9b257b7545"
down_revision: Union[str, None] = "6dedb0a8fc0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company", sa.Column("stock_name", sa.String(), nullable=True))
    op.add_column(
        "company",
        sa.Column("stock_price", sa.Numeric(precision=15, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "stock_price")
    op.drop_column("company", "stock_name")
    # ### end Alembic commands ###
