"""add user roles

Revision ID: 658f109913c4
Revises: fe818207607a
Create Date: 2025-06-10 13:50:44.472791

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "658f109913c4"
down_revision: Union[str, None] = "fe818207607a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = postgresql.ENUM("user", "admin", name="userrole")
    userrole.create(op.get_bind())

    op.add_column(
        "users",
        sa.Column(
            "role",
            userrole,
            nullable=False,
            server_default=sa.text("'user'"),  # <-- wrap in sa.text and quotes
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")

    # Drop the enum type
    userrole = postgresql.ENUM("user", "admin", name="userrole")
    userrole.drop(op.get_bind())  # ### end Alembic commands ###
