"""Update company table

Revision ID: b736285da0b3
Revises: 4a9b257b7545
Create Date: 2025-05-26 21:05:28.411273

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b736285da0b3"
down_revision: Union[str, None] = "4a9b257b7545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "image_url")
    # ### end Alembic commands ###
