"""Add subscription_end_date column

Revision ID: e139521e80c7
Revises: ee14ff784016
Create Date: 2025-05-19 14:31:47.916850

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e139521e80c7"
down_revision: Union[str, None] = "ee14ff784016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("subscription_end_date", sa.DateTime(), server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subscription_end_date")
    # ### end Alembic commands ###
