"""create investor relations tables

Revision ID: ee14ff784016
Revises: 682246dc78ed
Create Date: 2025-05-13 17:44:41.650721

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee14ff784016"
down_revision: Union[str, None] = "682246dc78ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("stock_name", sa.String(), nullable=True),
        sa.Column("stock_price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("ceo", sa.String(), nullable=True),
        sa.Column("po_box", sa.String(), nullable=True),
        sa.Column("year_founded", sa.String(), nullable=True),
        sa.Column("swift_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("swift_code"),
    )
    op.create_index(op.f("ix_company_email"), "company", ["email"], unique=True)
    op.create_index(op.f("ix_company_id"), "company", ["id"], unique=True)
    op.create_index(op.f("ix_company_name"), "company", ["name"], unique=False)
    op.create_index(op.f("ix_company_phone"), "company", ["phone"], unique=False)
    op.create_index(op.f("ix_company_sector"), "company", ["sector"], unique=False)
    op.create_table(
        "executives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("appointment_date", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executives_id"), "executives", ["id"], unique=True)
    op.create_index(op.f("ix_executives_name"), "executives", ["name"], unique=False)
    op.create_index(
        op.f("ix_executives_position"), "executives", ["position"], unique=False
    )
    op.create_table(
        "personnel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("appointment_date", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personnel_id"), "personnel", ["id"], unique=True)
    op.create_index(op.f("ix_personnel_name"), "personnel", ["name"], unique=False)
    op.create_index(op.f("ix_personnel_title"), "personnel", ["title"], unique=False)
    op.create_table(
        "shareholder_information",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("information", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shareholder_information_id"),
        "shareholder_information",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_shareholder_information_information"),
        "shareholder_information",
        ["information"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shareholder_information_information"),
        table_name="shareholder_information",
    )
    op.drop_index(
        op.f("ix_shareholder_information_id"), table_name="shareholder_information"
    )
    op.drop_table("shareholder_information")
    op.drop_index(op.f("ix_personnel_title"), table_name="personnel")
    op.drop_index(op.f("ix_personnel_name"), table_name="personnel")
    op.drop_index(op.f("ix_personnel_id"), table_name="personnel")
    op.drop_table("personnel")
    op.drop_index(op.f("ix_executives_position"), table_name="executives")
    op.drop_index(op.f("ix_executives_name"), table_name="executives")
    op.drop_index(op.f("ix_executives_id"), table_name="executives")
    op.drop_table("executives")
    op.drop_index(op.f("ix_company_sector"), table_name="company")
    op.drop_index(op.f("ix_company_phone"), table_name="company")
    op.drop_index(op.f("ix_company_name"), table_name="company")
    op.drop_index(op.f("ix_company_id"), table_name="company")
    op.drop_index(op.f("ix_company_email"), table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###
